// Re-export generated OG map so edge-functions can import from a stable path.
// Source is generated by scripts/generate-og-map.ts under functions/_data.
export { ogMap } from '../../functions/_data/og-map'
