// Auto-generated by scripts/generate-og-map.ts
// DO NOT EDIT MANUALLY
export const ogMap: Record<string, { title: string; thumbnailUrl: string; ogImagePath: string }> = {
  mmexport1773546909741: {
    title: 'mmexport1773546909741',
    thumbnailUrl: '/thumbnails/mmexport1773546909741.jpg',
    ogImagePath: '/og/mmexport1773546909741.png',
  },
  Image_1773546866578: {
    title: 'Image 1773546866578',
    thumbnailUrl: '/thumbnails/Image_1773546866578.jpg',
    ogImagePath: '/og/Image_1773546866578.png',
  },
  mmexport1773546892830: {
    title: 'mmexport1773546892830',
    thumbnailUrl: '/thumbnails/mmexport1773546892830.jpg',
    ogImagePath: '/og/mmexport1773546892830.png',
  },
  mmexport1773546901910: {
    title: 'mmexport1773546901910',
    thumbnailUrl: '/thumbnails/mmexport1773546901910.jpg',
    ogImagePath: '/og/mmexport1773546901910.png',
  },
  bluedog: {
    title: 'bluedog',
    thumbnailUrl: '/thumbnails/bluedog.jpg',
    ogImagePath: '/og/bluedog.png',
  },
  '1692101205472': {
    title: '1692101205472',
    thumbnailUrl: '/thumbnails/1692101205472.jpg',
    ogImagePath: '/og/1692101205472.png',
  },
  IMG_20240824_183329: {
    title: 'IMG 20240824 183329',
    thumbnailUrl: '/thumbnails/IMG_20240824_183329.jpg',
    ogImagePath: '/og/IMG_20240824_183329.png',
  },
  Lieall_20260327_122859866: {
    title: 'Lieall 20260327 122859866',
    thumbnailUrl: '/thumbnails/Lieall_20260327_122859866.jpg',
    ogImagePath: '/og/Lieall_20260327_122859866.png',
  },
  IMG_20251121_085052: {
    title: 'IMG 20251121 085052',
    thumbnailUrl: '/thumbnails/IMG_20251121_085052.jpg',
    ogImagePath: '/og/IMG_20251121_085052.png',
  },
  IMG20251006191746: {
    title: 'IMG20251006191746',
    thumbnailUrl: '/thumbnails/IMG20251006191746.jpg',
    ogImagePath: '/og/IMG20251006191746.png',
  },
  CRnall_20251006_163111459: {
    title: 'CRnall 20251006 163111459',
    thumbnailUrl: '/thumbnails/CRnall_20251006_163111459.jpg',
    ogImagePath: '/og/CRnall_20251006_163111459.png',
  },
  CRnall_20251006_162915449: {
    title: 'CRnall 20251006 162915449',
    thumbnailUrl: '/thumbnails/CRnall_20251006_162915449.jpg',
    ogImagePath: '/og/CRnall_20251006_162915449.png',
  },
  CRnall_20251006_145314732: {
    title: 'CRnall 20251006 145314732',
    thumbnailUrl: '/thumbnails/CRnall_20251006_145314732.jpg',
    ogImagePath: '/og/CRnall_20251006_145314732.png',
  },
  IMG_20251006_145829: {
    title: 'IMG 20251006 145829',
    thumbnailUrl: '/thumbnails/IMG_20251006_145829.jpg',
    ogImagePath: '/og/IMG_20251006_145829.png',
  },
  CRnall_20251006_120650829: {
    title: 'CRnall 20251006 120650829',
    thumbnailUrl: '/thumbnails/CRnall_20251006_120650829.jpg',
    ogImagePath: '/og/CRnall_20251006_120650829.png',
  },
  CRnall_20251006_111444356: {
    title: 'CRnall 20251006 111444356',
    thumbnailUrl: '/thumbnails/CRnall_20251006_111444356.jpg',
    ogImagePath: '/og/CRnall_20251006_111444356.png',
  },
  IMG_20251006_110829: {
    title: 'IMG 20251006 110829',
    thumbnailUrl: '/thumbnails/IMG_20251006_110829.jpg',
    ogImagePath: '/og/IMG_20251006_110829.png',
  },
  CRnall_20251006_110501942: {
    title: 'CRnall 20251006 110501942',
    thumbnailUrl: '/thumbnails/CRnall_20251006_110501942.jpg',
    ogImagePath: '/og/CRnall_20251006_110501942.png',
  },
  CRnall_20251006_104855164: {
    title: 'CRnall 20251006 104855164',
    thumbnailUrl: '/thumbnails/CRnall_20251006_104855164.jpg',
    ogImagePath: '/og/CRnall_20251006_104855164.png',
  },
  CRnall_20251006_104402315: {
    title: 'CRnall 20251006 104402315',
    thumbnailUrl: '/thumbnails/CRnall_20251006_104402315.jpg',
    ogImagePath: '/og/CRnall_20251006_104402315.png',
  },
  CRnall_20251006_104112313: {
    title: 'CRnall 20251006 104112313',
    thumbnailUrl: '/thumbnails/CRnall_20251006_104112313.jpg',
    ogImagePath: '/og/CRnall_20251006_104112313.png',
  },
  CRnall_20251006_103910019: {
    title: 'CRnall 20251006 103910019',
    thumbnailUrl: '/thumbnails/CRnall_20251006_103910019.jpg',
    ogImagePath: '/og/CRnall_20251006_103910019.png',
  },
  CRnall_20251006_102211155: {
    title: 'CRnall 20251006 102211155',
    thumbnailUrl: '/thumbnails/CRnall_20251006_102211155.jpg',
    ogImagePath: '/og/CRnall_20251006_102211155.png',
  },
  CRnall_20251006_102002599: {
    title: 'CRnall 20251006 102002599',
    thumbnailUrl: '/thumbnails/CRnall_20251006_102002599.jpg',
    ogImagePath: '/og/CRnall_20251006_102002599.png',
  },
  CRnall_20251006_100844531: {
    title: 'CRnall 20251006 100844531',
    thumbnailUrl: '/thumbnails/CRnall_20251006_100844531.jpg',
    ogImagePath: '/og/CRnall_20251006_100844531.png',
  },
  CRnall_20251006_095330953: {
    title: 'CRnall 20251006 095330953',
    thumbnailUrl: '/thumbnails/CRnall_20251006_095330953.jpg',
    ogImagePath: '/og/CRnall_20251006_095330953.png',
  },
  CRnall_20251006_094044673: {
    title: 'CRnall 20251006 094044673',
    thumbnailUrl: '/thumbnails/CRnall_20251006_094044673.jpg',
    ogImagePath: '/og/CRnall_20251006_094044673.png',
  },
  CRnall_20251006_093757114: {
    title: 'CRnall 20251006 093757114',
    thumbnailUrl: '/thumbnails/CRnall_20251006_093757114.jpg',
    ogImagePath: '/og/CRnall_20251006_093757114.png',
  },
  CRnall_20251006_084118319: {
    title: 'CRnall 20251006 084118319',
    thumbnailUrl: '/thumbnails/CRnall_20251006_084118319.jpg',
    ogImagePath: '/og/CRnall_20251006_084118319.png',
  },
  CRnall_20251006_083525190: {
    title: 'CRnall 20251006 083525190',
    thumbnailUrl: '/thumbnails/CRnall_20251006_083525190.jpg',
    ogImagePath: '/og/CRnall_20251006_083525190.png',
  },
  CRnall_20251006_083232451: {
    title: 'CRnall 20251006 083232451',
    thumbnailUrl: '/thumbnails/CRnall_20251006_083232451.jpg',
    ogImagePath: '/og/CRnall_20251006_083232451.png',
  },
  CRnall_20251006_082852023: {
    title: 'CRnall 20251006 082852023',
    thumbnailUrl: '/thumbnails/CRnall_20251006_082852023.jpg',
    ogImagePath: '/og/CRnall_20251006_082852023.png',
  },
  IMG_20251006_083817: {
    title: 'IMG 20251006 083817',
    thumbnailUrl: '/thumbnails/IMG_20251006_083817.jpg',
    ogImagePath: '/og/IMG_20251006_083817.png',
  },
  IMG_20251006_081736: {
    title: 'IMG 20251006 081736',
    thumbnailUrl: '/thumbnails/IMG_20251006_081736.jpg',
    ogImagePath: '/og/IMG_20251006_081736.png',
  },
  CRnall_20251006_075831793: {
    title: 'CRnall 20251006 075831793',
    thumbnailUrl: '/thumbnails/CRnall_20251006_075831793.jpg',
    ogImagePath: '/og/CRnall_20251006_075831793.png',
  },
  IMG20251006062207: {
    title: 'IMG20251006062207',
    thumbnailUrl: '/thumbnails/IMG20251006062207.jpg',
    ogImagePath: '/og/IMG20251006062207.png',
  },
  'CRnall_20250729_130309364 (1)': {
    title: 'CRnall 20250729 130309364 (1)',
    thumbnailUrl: '/thumbnails/CRnall_20250729_130309364 (1).jpg',
    ogImagePath: '/og/CRnall_20250729_130309364 (1).png',
  },
  CRnall_20250724_203129282: {
    title: 'CRnall 20250724 203129282',
    thumbnailUrl: '/thumbnails/CRnall_20250724_203129282.jpg',
    ogImagePath: '/og/CRnall_20250724_203129282.png',
  },
  IMG_20250909_151446: {
    title: 'IMG 20250909 151446',
    thumbnailUrl: '/thumbnails/IMG_20250909_151446.jpg',
    ogImagePath: '/og/IMG_20250909_151446.png',
  },
  IMG_20250610_211431: {
    title: 'IMG 20250610 211431',
    thumbnailUrl: '/thumbnails/IMG_20250610_211431.jpg',
    ogImagePath: '/og/IMG_20250610_211431.png',
  },
  IMG20250602234049: {
    title: 'IMG20250602234049',
    thumbnailUrl: '/thumbnails/IMG20250602234049.jpg',
    ogImagePath: '/og/IMG20250602234049.png',
  },
  CRnall_20250530_221125090: {
    title: 'CRnall 20250530 221125090',
    thumbnailUrl: '/thumbnails/CRnall_20250530_221125090.jpg',
    ogImagePath: '/og/CRnall_20250530_221125090.png',
  },
  IMG_20250529_230037: {
    title: 'IMG 20250529 230037',
    thumbnailUrl: '/thumbnails/IMG_20250529_230037.jpg',
    ogImagePath: '/og/IMG_20250529_230037.png',
  },
  CRnall_20250529_165035030: {
    title: 'CRnall 20250529 165035030',
    thumbnailUrl: '/thumbnails/CRnall_20250529_165035030.jpg',
    ogImagePath: '/og/CRnall_20250529_165035030.png',
  },
  CRnall_20250529_153442716: {
    title: 'CRnall 20250529 153442716',
    thumbnailUrl: '/thumbnails/CRnall_20250529_153442716.jpg',
    ogImagePath: '/og/CRnall_20250529_153442716.png',
  },
  IMG_20250501_215203: {
    title: 'IMG 20250501 215203',
    thumbnailUrl: '/thumbnails/IMG_20250501_215203.jpg',
    ogImagePath: '/og/IMG_20250501_215203.png',
  },
  'IMG_20250501_215154~2': {
    title: 'IMG 20250501 215154~2',
    thumbnailUrl: '/thumbnails/IMG_20250501_215154~2.jpg',
    ogImagePath: '/og/IMG_20250501_215154~2.png',
  },
  IMG_20250501_215144: {
    title: 'IMG 20250501 215144',
    thumbnailUrl: '/thumbnails/IMG_20250501_215144.jpg',
    ogImagePath: '/og/IMG_20250501_215144.png',
  },
  IMG_20250501_215132: {
    title: 'IMG 20250501 215132',
    thumbnailUrl: '/thumbnails/IMG_20250501_215132.jpg',
    ogImagePath: '/og/IMG_20250501_215132.png',
  },
  'IMG_20250501_215132~2': {
    title: 'IMG 20250501 215132~2',
    thumbnailUrl: '/thumbnails/IMG_20250501_215132~2.jpg',
    ogImagePath: '/og/IMG_20250501_215132~2.png',
  },
  IMG_20250423_205849: {
    title: 'IMG 20250423 205849',
    thumbnailUrl: '/thumbnails/IMG_20250423_205849.jpg',
    ogImagePath: '/og/IMG_20250423_205849.png',
  },
  IMG_20250425_070923: {
    title: 'IMG 20250425 070923',
    thumbnailUrl: '/thumbnails/IMG_20250425_070923.jpg',
    ogImagePath: '/og/IMG_20250425_070923.png',
  },
  'IMG_20250418_210738 (1)': {
    title: 'IMG 20250418 210738 (1)',
    thumbnailUrl: '/thumbnails/IMG_20250418_210738 (1).jpg',
    ogImagePath: '/og/IMG_20250418_210738 (1).png',
  },
  mmexport1744856357868: {
    title: 'mmexport1744856357868',
    thumbnailUrl: '/thumbnails/mmexport1744856357868.jpg',
    ogImagePath: '/og/mmexport1744856357868.png',
  },
  CRnall_20250404_193529810: {
    title: 'CRnall 20250404 193529810',
    thumbnailUrl: '/thumbnails/CRnall_20250404_193529810.jpg',
    ogImagePath: '/og/CRnall_20250404_193529810.png',
  },
  IMG20250404182604: {
    title: 'IMG20250404182604',
    thumbnailUrl: '/thumbnails/IMG20250404182604.jpg',
    ogImagePath: '/og/IMG20250404182604.png',
  },
  IMG_20250203_145251: {
    title: 'IMG 20250203 145251',
    thumbnailUrl: '/thumbnails/IMG_20250203_145251.jpg',
    ogImagePath: '/og/IMG_20250203_145251.png',
  },
  IMG_20250203_145132: {
    title: 'IMG 20250203 145132',
    thumbnailUrl: '/thumbnails/IMG_20250203_145132.jpg',
    ogImagePath: '/og/IMG_20250203_145132.png',
  },
  IMG_20250119_192741: {
    title: 'IMG 20250119 192741',
    thumbnailUrl: '/thumbnails/IMG_20250119_192741.jpg',
    ogImagePath: '/og/IMG_20250119_192741.png',
  },
  CRnall_20250114_121910673: {
    title: 'CRnall 20250114 121910673',
    thumbnailUrl: '/thumbnails/CRnall_20250114_121910673.jpg',
    ogImagePath: '/og/CRnall_20250114_121910673.png',
  },
  IMG_20251013_193932: {
    title: 'IMG 20251013 193932',
    thumbnailUrl: '/thumbnails/IMG_20251013_193932.jpg',
    ogImagePath: '/og/IMG_20251013_193932.png',
  },
  mmexport1735739408233: {
    title: 'mmexport1735739408233',
    thumbnailUrl: '/thumbnails/mmexport1735739408233.jpg',
    ogImagePath: '/og/mmexport1735739408233.png',
  },
  IMG_20241205_142454: {
    title: 'IMG 20241205 142454',
    thumbnailUrl: '/thumbnails/IMG_20241205_142454.jpg',
    ogImagePath: '/og/IMG_20241205_142454.png',
  },
  CRnall_20241205_142152302: {
    title: 'CRnall 20241205 142152302',
    thumbnailUrl: '/thumbnails/CRnall_20241205_142152302.jpg',
    ogImagePath: '/og/CRnall_20241205_142152302.png',
  },
  CRnall_20241205_141959169: {
    title: 'CRnall 20241205 141959169',
    thumbnailUrl: '/thumbnails/CRnall_20241205_141959169.jpg',
    ogImagePath: '/og/CRnall_20241205_141959169.png',
  },
  CRnall_20241205_141903959: {
    title: 'CRnall 20241205 141903959',
    thumbnailUrl: '/thumbnails/CRnall_20241205_141903959.jpg',
    ogImagePath: '/og/CRnall_20241205_141903959.png',
  },
  IMG_20241130_151811: {
    title: 'IMG 20241130 151811',
    thumbnailUrl: '/thumbnails/IMG_20241130_151811.jpg',
    ogImagePath: '/og/IMG_20241130_151811.png',
  },
  IMG_20241130_001306: {
    title: 'IMG 20241130 001306',
    thumbnailUrl: '/thumbnails/IMG_20241130_001306.jpg',
    ogImagePath: '/og/IMG_20241130_001306.png',
  },
  CRnall_20241125_102317767: {
    title: 'CRnall 20241125 102317767',
    thumbnailUrl: '/thumbnails/CRnall_20241125_102317767.jpg',
    ogImagePath: '/og/CRnall_20241125_102317767.png',
  },
  CRnall_20241124_215027789: {
    title: 'CRnall 20241124 215027789',
    thumbnailUrl: '/thumbnails/CRnall_20241124_215027789.jpg',
    ogImagePath: '/og/CRnall_20241124_215027789.png',
  },
  CRnall_20241118_075415685: {
    title: 'CRnall 20241118 075415685',
    thumbnailUrl: '/thumbnails/CRnall_20241118_075415685.jpg',
    ogImagePath: '/og/CRnall_20241118_075415685.png',
  },
  IMG_20241102_080728: {
    title: 'IMG 20241102 080728',
    thumbnailUrl: '/thumbnails/IMG_20241102_080728.jpg',
    ogImagePath: '/og/IMG_20241102_080728.png',
  },
  IMG_20241115_100552: {
    title: 'IMG 20241115 100552',
    thumbnailUrl: '/thumbnails/IMG_20241115_100552.jpg',
    ogImagePath: '/og/IMG_20241115_100552.png',
  },
  IMG_20241021_070129: {
    title: 'IMG 20241021 070129',
    thumbnailUrl: '/thumbnails/IMG_20241021_070129.jpg',
    ogImagePath: '/og/IMG_20241021_070129.png',
  },
  CRnall_20240828_193901565: {
    title: 'CRnall 20240828 193901565',
    thumbnailUrl: '/thumbnails/CRnall_20240828_193901565.jpg',
    ogImagePath: '/og/CRnall_20240828_193901565.png',
  },
  CRnall_20240828_193546492: {
    title: 'CRnall 20240828 193546492',
    thumbnailUrl: '/thumbnails/CRnall_20240828_193546492.jpg',
    ogImagePath: '/og/CRnall_20240828_193546492.png',
  },
  CRnall_20240828_181958132: {
    title: 'CRnall 20240828 181958132',
    thumbnailUrl: '/thumbnails/CRnall_20240828_181958132.jpg',
    ogImagePath: '/og/CRnall_20240828_181958132.png',
  },
  d125a728dd0c1c3d8ee677b62f7f79bd: {
    title: 'd125a728dd0c1c3d8ee677b62f7f79bd',
    thumbnailUrl: '/thumbnails/d125a728dd0c1c3d8ee677b62f7f79bd.jpg',
    ogImagePath: '/og/d125a728dd0c1c3d8ee677b62f7f79bd.png',
  },
  骷髅: {
    title: '骷髅',
    thumbnailUrl: '/thumbnails/骷髅.jpg',
    ogImagePath: '/og/骷髅.png',
  },
}
