import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { renderOgImage } from '../packages/renderer/src/og/og.renderer'
import type { ExifInfo } from '../packages/renderer/src/og/og.template'
import geistMedium from './og-fonts/Geist-Medium'
import geistRegular from './og-fonts/Geist-Regular'
import pingFangSC from './og-fonts/PingFangSC'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')

const fonts = [
  { name: 'Geist', data: geistRegular, style: 'normal' as const, weight: 400 },
  { name: 'Geist', data: geistMedium, style: 'normal' as const, weight: 500 },
  { name: 'HarmonyOS Sans SC', data: pingFangSC, style: 'normal' as const, weight: 400 },
]

interface ManifestPhoto {
  id: string
  title: string
  thumbnailUrl: string
  originalUrl?: string
  width?: number
  height?: number
  exif?: Record<string, unknown>
  tags?: string[]
  ogImageUrl?: string
}

interface Manifest {
  data: ManifestPhoto[]
}

async function main() {
  const manifestPath = path.join(rootDir, 'apps/web/src/data/photos-manifest.json')
  const manifest: Manifest = JSON.parse(await readFile(manifestPath, 'utf-8'))

  const ogDir = path.join(rootDir, 'apps/web/public/og')
  await mkdir(ogDir, { recursive: true })

  // Read site config for site name
  let siteName = 'Afilmory'
  let accentColor = '#007bff'
  try {
    const configPath = path.join(rootDir, 'config.json')
    const config = JSON.parse(await readFile(configPath, 'utf-8'))
    siteName = config.title || config.name || siteName
    accentColor = config.accentColor || accentColor
  } catch {
    // config.json is optional, use defaults
  }

  const ogMapEntries: Record<string, { title: string; thumbnailUrl: string; ogImagePath: string }> = {}

  console.info(`📸 Generating OG images for ${manifest.data.length} photos...`)

  let generated = 0
  let skipped = 0

  for (const photo of manifest.data) {
    const width = photo.width ?? 1
    const height = photo.height ?? 1

    const exifInfo: ExifInfo | undefined = photo.exif
      ? {
          focalLength: photo.exif.FocalLength35mm ? `${photo.exif.FocalLength35mm}` : undefined,
          aperture: photo.exif.FNumber ? `f/${photo.exif.FNumber}` : undefined,
          iso: photo.exif.ISO ? `${photo.exif.ISO}` : undefined,
          shutterSpeed: photo.exif.ExposureTime ? `${photo.exif.ExposureTime}s` : undefined,
          camera: photo.exif.Model ? `${photo.exif.Model}` : undefined,
        }
      : undefined

    // Fetch thumbnail as data URL for the template
    let thumbnailSrc: string | undefined
    try {
      const thumbPath = path.join(rootDir, 'apps/web/public', photo.thumbnailUrl)
      const thumbData = await readFile(thumbPath)
      const ext = path.extname(photo.thumbnailUrl).slice(1) || 'jpg'
      thumbnailSrc = `data:image/${ext === 'jpg' ? 'jpeg' : ext};base64,${thumbData.toString('base64')}`
    } catch {
      // Skip OG image generation if thumbnail not found
      skipped++
      continue
    }

    try {
      const png = await renderOgImage({
        template: {
          photoTitle: photo.title,
          siteName,
          tags: photo.tags?.slice(0, 3) ?? [],
          formattedDate: undefined,
          exifInfo,
          thumbnailSrc,
          photoDimensions: { width, height },
          accentColor,
        },
        fonts,
      })

      const ogImagePath = `/og/${photo.id}.png`
      await writeFile(path.join(rootDir, 'apps/web/public', ogImagePath), png)

      ogMapEntries[photo.id] = {
        title: photo.title,
        thumbnailUrl: photo.thumbnailUrl,
        ogImagePath,
      }

      generated++
    } catch (err) {
      console.error(`Failed to generate OG image for ${photo.id}:`, err)
      skipped++
    }
  }

  // Generate the OG map TypeScript file for EdgeOne functions
  const functionsDataDir = path.join(rootDir, 'functions/_data')
  await mkdir(functionsDataDir, { recursive: true })

  const mapContent = `// Auto-generated by scripts/generate-og-map.ts
// DO NOT EDIT MANUALLY
export const ogMap: Record<string, { title: string; thumbnailUrl: string; ogImagePath: string }> = ${JSON.stringify(ogMapEntries, null, 2)}
`

  await writeFile(path.join(functionsDataDir, 'og-map.ts'), mapContent)

  console.info(`✅ OG map generated: ${generated} images, ${skipped} skipped, total ${manifest.data.length} photos`)
  console.info(`📁 OG images: apps/web/public/og/`)
  console.info(`📄 OG map: functions/_data/og-map.ts`)
}

main().catch((err) => {
  console.error('Failed to generate OG map:', err)
  throw err
})
