import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { renderOgImage } from '../packages/renderer/src/og/og.renderer'
import type { ExifInfo } from '../packages/renderer/src/og/og.template'
import geistMedium from './og-fonts/Geist-Medium'
import geistRegular from './og-fonts/Geist-Regular'
import pingFangSC from './og-fonts/PingFangSC'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')

const fonts = [
  { name: 'Geist', data: geistRegular, style: 'normal' as const, weight: 400 },
  { name: 'Geist', data: geistMedium, style: 'normal' as const, weight: 500 },
  { name: 'HarmonyOS Sans SC', data: pingFangSC, style: 'normal' as const, weight: 400 },
]

interface ManifestPhoto {
  id: string
  title: string
  thumbnailUrl: string
  originalUrl?: string
  width?: number
  height?: number
  exif?: Record<string, unknown>
  tags?: string[]
  ogImageUrl?: string
}

interface Manifest {
  data: ManifestPhoto[]
}

async function canReuseOgImage(thumbnailPath: string, ogOutputPath: string): Promise<boolean> {
  try {
    const [thumbnailStat, ogStat] = await Promise.all([stat(thumbnailPath), stat(ogOutputPath)])
    return ogStat.mtimeMs >= thumbnailStat.mtimeMs
  } catch {
    return false
  }
}

async function main() {
  const manifestPath = path.join(rootDir, 'apps/web/src/data/photos-manifest.json')
  const manifest: Manifest = JSON.parse(await readFile(manifestPath, 'utf-8'))

  const ogDir = path.join(rootDir, 'apps/web/public/og')
  await mkdir(ogDir, { recursive: true })

  let siteName = 'Afilmory'
  let accentColor = '#007bff'
  try {
    const configPath = path.join(rootDir, 'config.json')
    const config = JSON.parse(await readFile(configPath, 'utf-8'))
    siteName = config.title || config.name || siteName
    accentColor = config.accentColor || accentColor
  } catch {
    // config.json is optional, use defaults
  }

  const ogMapEntries: Record<string, { title: string; thumbnailUrl: string; ogImagePath: string }> = {}

  console.info(`Generating OG images for ${manifest.data.length} photos...`)

  let generated = 0
  let reused = 0
  let skipped = 0

  for (const photo of manifest.data) {
    const width = photo.width ?? 1
    const height = photo.height ?? 1
    const thumbPath = path.join(rootDir, 'apps/web/public', photo.thumbnailUrl)
    const ogImagePath = `/og/${photo.id}.png`
    const ogOutputPath = path.join(rootDir, 'apps/web/public', ogImagePath)

    if (await canReuseOgImage(thumbPath, ogOutputPath)) {
      ogMapEntries[photo.id] = {
        title: photo.title,
        thumbnailUrl: photo.thumbnailUrl,
        ogImagePath,
      }
      reused++
      continue
    }

    const exifInfo: ExifInfo | undefined = photo.exif
      ? {
          focalLength: photo.exif.FocalLength35mm ? `${photo.exif.FocalLength35mm}` : undefined,
          aperture: photo.exif.FNumber ? `f/${photo.exif.FNumber}` : undefined,
          iso: photo.exif.ISO ? `${photo.exif.ISO}` : undefined,
          shutterSpeed: photo.exif.ExposureTime ? `${photo.exif.ExposureTime}s` : undefined,
          camera: photo.exif.Model ? `${photo.exif.Model}` : undefined,
        }
      : undefined

    let thumbnailSrc: string | undefined
    try {
      const thumbData = await readFile(thumbPath)
      const ext = path.extname(photo.thumbnailUrl).slice(1) || 'jpg'
      thumbnailSrc = `data:image/${ext === 'jpg' ? 'jpeg' : ext};base64,${thumbData.toString('base64')}`
    } catch {
      skipped++
      continue
    }

    try {
      const png = await renderOgImage({
        template: {
          photoTitle: photo.title,
          siteName,
          tags: photo.tags?.slice(0, 3) ?? [],
          formattedDate: undefined,
          exifInfo,
          thumbnailSrc,
          photoDimensions: { width, height },
          accentColor,
        },
        fonts,
      })

      await writeFile(ogOutputPath, png)

      ogMapEntries[photo.id] = {
        title: photo.title,
        thumbnailUrl: photo.thumbnailUrl,
        ogImagePath,
      }

      generated++
    } catch (err) {
      console.error(`Failed to generate OG image for ${photo.id}:`, err)
      skipped++
    }
  }

  const edgeFunctionsDataDir = path.join(rootDir, 'edge-functions/_data')
  await mkdir(edgeFunctionsDataDir, { recursive: true })

  const mapContent = `// Auto-generated by scripts/generate-og-map.ts
// DO NOT EDIT MANUALLY
export const ogMap: Record<string, { title: string; thumbnailUrl: string; ogImagePath: string }> = ${JSON.stringify(ogMapEntries, null, 2)}
`

  await writeFile(path.join(edgeFunctionsDataDir, 'og-map.ts'), mapContent)

  console.info(
    `OG map generated: ${generated} rendered, ${reused} reused, ${skipped} skipped, total ${manifest.data.length} photos`,
  )
  console.info('OG images: apps/web/public/og/')
  console.info('OG map: edge-functions/_data/og-map.ts')
}

main().catch((err) => {
  console.error('Failed to generate OG map:', err)
  throw err
})
